# Schema for the configuration files of the Google Places Autocomplete module.
google_places_autocomplete.settings:
  type: config_object
  label: 'Google Places Autocomplete settings'
  mapping:
    api_key:
      type: string
      label: 'API Key'
