<?php

/**
 * @file
 * Functions to support theming in the axalta theme.
 */

use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function axalta_preprocess_html(array &$variables): void {

  $current_route = \Drupal::routeMatch();

  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    // Füge die Node ID als Variable hinzu
    $variables['node_id'] = $node->id();
  }

  // Add 'page-NODE-TYPE' class to body.
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof Node) {
    $variables['attributes']['class'][] = 'node--' . $node->getType();
    $variables['attributes']['class'][] = 'node--' . $node->id();
  }

  // Check if regions are filled and add class to body.
  if (!empty($variables['page']['highlighted_top'])) {
    $variables['attributes']['class'][] = 'highlighted-top--visible';
  }

  // Add class to front page.
  if (\Drupal::service('path.matcher')->isFrontPage()) {
    $variables['attributes']['class'][] = 'frontpage';
  }

  // Add class to body if header media slider is set on page.
  $has_header_slider = FALSE;
  switch ($current_route->getRouteName()) {
    // Node route:
    case 'entity.node.canonical':
      /** @var $entity Node */
      if ($entity = \Drupal::routeMatch()->getParameter('node')) {
        if (
          $entity instanceof Node
          && $entity->hasField('field_mediaslider')
          && !empty($entity->get('field_mediaslider')->getValue())
          && $entity->get('field_mediaslider')->getValue()[0])
        {
          // Default slider fields.
          $has_header_slider = TRUE;
        } else if ($entity instanceof Node
          && $entity->bundle() === 'vacancy'
          && $entity->hasField('field_image'))
        {
          // Node, type 'vacancy' with fixed image field.
          $has_header_slider = TRUE;
        }
      }
      break;
  }

  if ($has_header_slider) {
    $variables['attributes']['class'][] = 'header-slider--visible';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 *
 * Make forms themeable:
 * e.g. => form--user-login-form.html.twig
 */
function axalta_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if (!empty($variables['element']['#form_id'])) {
    $suggestions[] = 'form__' . $variables['element']['#form_id'];
  }
}

/**
 * Implementation of hook_theme_suggestions_hook().
 */
function axalta_theme_suggestions_block_alter(&$suggestions, $variables) {
  // Add template suggestions for custom block bundles.
  if (isset($variables['elements']['content']['#block_content'])) {
    array_splice($suggestions, 1, 0, 'block__bundle__' . $variables['elements']['content']['#block_content']->bundle());
  }
}

/**
 * Implements hook_js_alter().
 */
function axalta_js_alter(&$javascript, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  // dsm($javascript);

  $remove = [
    // Contrib:
    // Drupal core.
    'core/misc/tableresponsive.js',
    'core/misc/progress.js',
  ];
  foreach ($remove as $item) {
    unset($javascript[$item]);
  }
}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function axalta_preprocess_node(&$variables) {}

/**
 * Use language code for the language switcher
 */
function axalta_preprocess_links__language_block(&$variables) {
  foreach ($variables['links'] as $i => $link) {
    // @var \Drupal\language\Entity\ConfigurableLanguage $linkLanguage
    $linkLanguage = $link['link']['#options']['language'];
    $variables['links'][$i]['link']['#title'] = strtoupper($linkLanguage->get('id'));
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function axalta_preprocess_paragraph(&$variables) {

  // Get paragraph.
  /** @var Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['elements']['#paragraph'];

  // dsm($paragraph->getType());
  switch ($paragraph->getType()) {
    case 'timeline':
      // Timeline paragraph:
      // Add library.
      $variables['#attached']['library'][] = 'axalta/timeline_slider';
      break;
    case 'testimonials':
      // Testimonials paragraph:
      // Add library.
      $variables['#attached']['library'][] = 'axalta/testimonials_slider';
      break;
  }
}
